import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "antd/dist/reset.css";
import { i18n } from "~/lang/i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return i18n.locales.map(locale => ({ lang: locale }));
}

export default function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: { lang: string };
}) {
    return (
        <html lang={params.lang}>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
